### PR TITLE
Implement read and write json for books

### PR DESCRIPTION
**Pull request by Alejuda**
Hi partners! In this branch, I created the feature to store Books data into JSON files and added options to add book on console.

### CODE REVIEW

**Review by Mar12358 — DISMISSED** [review]
See review in the next comment

**Review by Mar12358 — COMMENTED** [review]
## Hi @Alejuda! 
Great Job so far, you are almost there! 💯 
so-close-jim-halpert
Nice implementation for methods:
✅ add_book
✅ load_books_file
✅ write_books_file
### For listing the books, please check this screenshot:
image
**[REQUIRED CHANGE] ::** You could remove the Tittle and also print each book in only one line.
It seems that only removing the title, the line stops being too long. This way:
`puts "#{index}) Publisher: #{book.publisher}, Cover state: #{book.cover_state}, Date: #{book.publish_date}"`




Please, implement that change before for merging! 🙏 

Happy Coding! 🎉

**Comment by Alejuda** [comment]
Hi @Mar12358, thanks for your review. I already implement the required change and is working as expected.

**Review by Mar12358 — APPROVED** [review]
### Hi @Alejuda !
Congratulations 🥳 
It's approved 💯 
Time to merge it! 🥇 
Happy coding! 🎉

**Pull request merged**
